import Head from 'next/head'
import Image from 'next/image'
import React from 'react';

const Header = ({ data }) => {
  return (
    <div className="p-6 md:p-10 lg:p-16 mt-12 relative">
      <Head>
        <title>FiftyFifty Funding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-4xl md:text-6xl lg:text-8xl line text-white font-bold uppercase">
        Welcome to <span className="text-[#01BFF1]">FiftyFifty,</span><br className="hidden md:block"/>
        <span className='text-[#c3c3c3]'>where we fund</span> your <br className="hidden md:block"/>
        business aspirations <br className="hidden md:block"/>
        <span className='text-[#c3c3c3]'>while you retain</span> full <br className="hidden md:block"/>
        operational control.
      </h1>

      {/* Subtext */}
      <p className="text-white mt-2 md:mt-5 mb-10 md:mb-20 text-[16px] md:text-[18px] lg:text-[20px]">
        {data.HeaderComponent.TextBlock}
      </p>

    </div>
  );
};

export default Header;
