import Head from 'next/head'
import Image from 'next/image'

import React from 'react';

const Header = () => {
  return (
    <div className="bg-blue-500 p-6">
      <Head>
        <title>FiftyFifty Funding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl text-white font-bold">WELCOME TO FIFTYFIFTY</h1>
      <p className="text-white mt-2">Where we fund your business aspirations...</p>
    </div>
  );
};

export default Header;